#!/bin/bash
# .bashrc
# Run when an interactive shell that is not a login shell executes.
# When a login shell executes .bash_profile is read first.
# Source this file in .bash_profile
# See `man bash` /INVOCATIONS

export EDITOR="nvim"
# Don't use stow-symlinks with weechat config, just point right at it. This is
# because Docker can't see outside of the volume, so the symlinks break.
export WEECHAT_HOME="$HOME/.dotfiles/weechat"
export SUP_LOG_DIR="$WEECHAT_HOME/logs"
export SUP_DIR="$HOME/w/standup"
export JDIR="$HOME/Documents/journal"
export JDIR_ENTRIES="$JDIR/entries"

export HOSTNAME_CT_LT="ct-lt-02087"
HOSTNAME_MBP="tomp-mbp.mynet"

# If we are on macOS, do some more overriding setup. Call at the end.
if_macos_setup()
{
	if [ "$(uname -s)" != "Darwin" ]; then
		return
	fi
	include "/usr/local/etc/bash_completion"
	alias ls="ls -G"
}

# append string to PATH, if PATH does not already contain string
pathadd()
{
	declare -r suffix="$1"

	# If PATH is empty, set to suffix
	case ":${PATH:=$suffix}:" in
	*":$suffix:"*) :;;        # PATH already contains suffix.
	*) PATH="$PATH:$suffix";; # Append suffix to PATH.
	esac
}

ps1()
{
	# Custom PS1 for the following machines
	case "$HOSTNAME" in
	"$HOSTNAME_MBP"|"$HOSTNAME_CT_LT")
		PS1='\w\[\033[33m\]\$\[\033[0m\] '
		return
		;;
	esac
}

source "/etc/bashrc"
source "$HOME/.bash_aliases"
source "$HOME/journal/journal.env"

pathadd "$HOME/.local/bin"
pathadd "$HOME/.cargo/bin"

ps1

if_macos_setup

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=
