#!/bin/bash
# utilities for managing standups
export SUP_FILE="$HOME/w/standup.d/ts005.txt"
export SUP_LOG="/home/tpreston/.config/hexchat/logs/codethink/#ts005.log"
export SUP_AUTHOR="Thomas Preston"
export SUP_BRANCH="master"
export SUP_GCODE="ts005"
export SUP_PCODE="kernel"
export SUP_WIKI_URL="https://gitlab.codethink.co.uk/$SUP_GCODE/$SUP_PCODE/wikis/log/standup_%s"

sup()
{
	if [ -z "$1" ]; then
		$EDITOR $SUP_FILE
	else
		cat $SUP_FILE
		grep -Ei "^#+ $1" $SUP_FILE
	fi
}


sup_format()
{
	local standup=""

	if [ -n "$SUP_LOG" ]; then
		standup="$SUP_LOG"
	elif [ -n "$1" ]; then
		standup="$1"
	else
		(>&2 echo "No standup specified")
		printf "Usage:\n\n      $0  hexchat_log\n\n"
		exit 1
	fi

	cat << EOF
# Present #

* Michael Drake (tlsa)
* Tom Eccles (ecclescake)
* Thomas Preston (tpreston)

# Absent #

# Reports #
EOF

	in_discussion=0
	while read line; do
		# debug
		#(>&2 echo "dbg:$in_discussion:$line")
		if [ $in_discussion = 0 ]; then
			# not in discussion
			line=$(echo "$line" | cut -f 2- -)

			if [[ "$line" == \#* ]]; then
				# if person name heading then leave a gap
				echo
			fi

			echo "$line"

			if echo "$line" | grep -qi "# Dis"; then
				# start discussion mode
				in_discussion=1
				echo
			fi

		else
			# in discussion, don't edit out the names
			discussion_line=$(echo $line | cut -d" " -f 4- -)
			echo "  $discussion_line"
			echo $line | grep -Eq "EOF|EOS|tpreston.*standup ends" && break
		fi
	done < <(tac "$standup" | awk "!old {print \$0}; /# $SUP_AUTHOR/ {old = 1};" | tac)
	echo
}

sup_commit_push()
{
	# add, commit and push a standup log
	local suplog=$1
	local message="$2"
	if [ -z "$suplog" ]; then
		echo "usage: sup_commit_push standup-log"
		return 1
	fi
	if [ -z "$message" ]; then
		message="Add standup log for $(date +%Y-%m-%d)"
	fi
	if [ "$(git rev-parse --abbrev-ref HEAD)" != "$SUP_BRANCH" ]; then
		echo "Not in $SUP_BRANCH branch, aborting."
		return 2
	fi
	git pull
	git add $suplog
	git commit -m "$message"
	git push origin $SUP_BRANCH
	printf "$SUP_WIKI_URL\n" $(date +%Y%m%d)
}
